#This Travis config template file was taken from https://github.com/FriendsOfCake/travis
language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
  - php: 5.4
    env: PHPCS=1 DEFAULT=0

  - php: 5.5
    env: COVERALLS=1 DEFAULT=0

  - php: 5.6
    env: COVERALLS=1 DEFAULT=0

before_install: phpenv config-add tests/testconfig.ini

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - composer update

services:
  - mongodb

before_script:
  - printf "\n" | pecl install mongo
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - mkdir -p build/logs

  - phpenv rehash
  - set +H
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --configuration phpunit.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --stderr --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false